### ISSUE TITLE
Disable LED on pro micro

### ISSUE THREAD

**Issue by peer69** [AlBundy33/TruckShifter#1]
By adding 

>     PORTD |= (1<<PORTD5);
>     PORTB |= (1<<PORTB0);
>     DDRD &= ~(1<<DDD5);
>     DDRB &= ~(1<<DDB0);

to the setup block you can disable the lower LED of the pro micro. It bothered me seeing red light coming from the bottom of the shifter. 
The power LED on the upper part cant be turned off in software though afaik, therefore I used some tape over the LED. Disabling the bottom LED and having the pro micro placed facing inwards the shifter might do the trick as well. I just didn't want to rewire it.

**Comment by AlBundy33** [comment]
where did you get this information from?

**Comment by peer69** [comment]
Been digging through some forum posts yesterday, probably from here: https://arduino.stackexchange.com/questions/3434/leonardo-disable-tx-and-rx-led

Tried it already, works well for me.

**Comment by AlBundy33** [comment]
I'm not at the PC right now but have you tried just to call the mentioned macros?
```
TXLED0;
RXLED0;
```

**Comment by peer69** [comment]
Yes, did nothing for me. Somebody mentioned this would work by selecting Arduino Micro as board but I haven't tried this after the method I mentioned did the trick. Not sure this is the "best" method to achieve this though.

**Comment by AlBundy33** [comment]
in arduino_pins.h the macros are defined as
```
#define TX_RX_LED_INIT	DDRD |= (1<<5), DDRB |= (1<<0)
#define TXLED0			PORTD |= (1<<5)
#define TXLED1			PORTD &= ~(1<<5)
#define RXLED0			PORTB |= (1<<0)
#define RXLED1			PORTB &= ~(1<<0)
```
where TX_RX_LED_INIT sets them as output and your code sets them as input an therefore the LEDs are off.
I've accepted your PR and added some comments. 👍
